name: whatsapp_bot_flutter
description: Whatsapp bot using puppeteer and whatsapp web scraping with flutter desktop/web and dart projects support
version: 2.0.1
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  puppeteer: ^3.0.0
  whatsapp_bot_platform_interface: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
